name: test-pkg-and-coverage

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  test-pkg-and-coverage:
   uses: Felixmil/Workflows/.github/workflows/test-pkg-and-coverage.yml@add-codecov-token-input
   with:
     install-pksim: true
     install-rClr: true
     extra-packages: |
       ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
       tlf=github::Open-Systems-Pharmacology/TLF-Library
       ospsuite=github::Open-Systems-Pharmacology/OSPSuite-R
       ospsuite.parameteridentification=github::Open-Systems-Pharmacology/OSPSuite.ParameterIdentification
   secrets:
     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN}}
